### PR TITLE
Update 2020-07-31-kubeflow-1.1-blog-post.md

### PR DESCRIPTION
**Pull request by jbottum**
3 updates, added section for KF Serving, updated Ant Financial to Ant Technology Group and added Dan Sun as contributor.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Thanks. I updated it to "Ant Group" since that's the official name.

**Comment by terrytangyuan** [comment]
The conflict is due to the markdown being removed in https://github.com/kubeflow/blog/pull/22.

**Comment by hamelsmu** [comment]
I can help resolve this conflict since it appears to be straight forward

**Comment by hamelsmu** [comment]
@jbottum I went ahead and resolved conflicts in favor of everything in this branch and merged it for you 🙇  Great post!

**Pull request merged**
