### PR TITLE
Create 2020-07-27-lineage-tracking.ipynb

### PR DESCRIPTION
**Pull request by Swikar**
Please let me know any changes or suggestion

### CODE REVIEW

**Comment by hamelsmu** [comment]
This PR closes #5106

**Comment by Swikar** [comment]
> @Swikar Looks like you did not test your notebook locally before submitting it to this PR

Conversion .ipynb to posts fails

**Comment by hamelsmu** [comment]
> Conversion .ipynb to posts fails

Did you try to debug it?  What steps did you try to use to debug this

**Pull request closed without merging**
