### PR TITLE
Fix OWNERS file

### LINKED ISSUE #14: Clarification for reviewing/approval process
Currently in README, we have the following:
> A group of designated subject matter experts will review.
> A Google representative will provide the final approval.

We should probably clarify who these people are and how to request for their reviews/approvals. Perhaps define a OWNERS file would help?

### PR DESCRIPTION
**Pull request by terrytangyuan**
Fixes #14.

### CODE REVIEW

**Comment by jlewi** [comment]
Much obliged. Not sure I can approve this but here goes
/lgtm
/approve

**Comment by Jeffwan** [comment]
em.. Seems no one can approve it now.

**Pull request merged**
