### PR TITLE
Update Jeffwan’s company name and add more details for WG-training

### PR DESCRIPTION
**Pull request by Jeffwan**
Forget to change my company name. I recently leave AWS and join Bytedance.

Add more important fixes and features in WG-training

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by Jeffwan** [comment]
@jbottum Who can approve this PR?

**Comment by Jeffwan** [comment]
@jbottum 

Can you manually merge it?

**Comment by jbottum** [comment]
@Jeffwan I merged this

**Pull request merged**
