### PR TITLE
1.2 Blog Post

### PR DESCRIPTION
**Pull request by jbottum**
Initial content for blog post, still needs some editing, formatting and images.    original content was from this google doc, https://docs.google.com/document/d/1fMAqZ9hv0p22TA6uMM2gpii65pMPiKJAKxSQ6e6RFho/edit?ts=5fb4991b

### CODE REVIEW

**Comment by jbottum** [comment]
@hamelsmu now have pull request created but missing the images and need to improve some text and formatting.

**Review by jbottum — COMMENTED** [review]
Improved format and content.

**Comment by jbottum** [comment]
@hamelsmu ok, this still needs some work...from others who are providing content, plus I think the format and are probably some typos.  Do I just alert the others that the PR is open and they can make their edits ?  or do I merge the pull request and then iterate after its merged ?

**Comment by jbottum** [comment]
@hamelsmu Hi Hamel - I merged this PR and should not have.   I think I should hide it and let people update it.   How do I hide it...i.e. You can hide a blog post from the home page by setting the front matter hide to true.

**Comment by hamelsmu** [comment]
Hi Josh may I suggest you get an engineer on your team to assist you with
this process.  I unfortunately do not have access to a computer for a while

**Pull request merged**
