### PR TITLE
Update 2020-07-31-kubeflow-1.1-blog-post.md

### PR DESCRIPTION
**Pull request by jbottum**
@andreyvelich @krishnadurai Added lines on Katib improvements, line 11 and lines 17 to 29, added Andrey and Krishna to post contributors. Please feel free to provide comments and help improve.

### CODE REVIEW

**Comment by hamelsmu** [comment]
You need to unhide this post in the front matter perhaps someone can help
you do that needs to be

hide: false

**Comment by hamelsmu** [comment]
Also please visit the README to understand all the configuration options https://github.com/fastai/fastpages

**Comment by jbottum** [comment]
@hamelsmu I am confused, I thought that hide = false would post the new content.   should hide = true ?

**Comment by hamelsmu** [comment]
I didn’t see that was changed in the diff.  On my phone so not looking at
the file closely.

Just make sure that hide: false and you should be good to go

**Pull request merged**
