### PR TITLE
Fixes typos in kubeflow install blog

### PR DESCRIPTION
**Pull request by deepk2u**
@jbottum I have tried to fix all the typos and used Grammarly to fix some of the grammar as well, let me know if you still see any other issues. 

Thanks for pointing it out though.

### CODE REVIEW

**Comment by deepk2u** [comment]
Pinging @kramachandran for approval.

**Comment by deepk2u** [comment]
Pinging @kramachandran @james-jwu for approval

**Comment by deepk2u** [comment]
@james-jwu you need to mention `approved` you missed `ed` in your comment.

**Comment by deepk2u** [comment]
@james-jwu usually it gets auto merged after the approval, not sure what’s wrong 

@theadactyl  approved last one like this: https://github.com/kubeflow/blog/pull/91#issuecomment-845394070

does it need new line? not sure!

**Comment by james-jwu** [comment]
I manually applied the LGTM and Approved labels.

**Pull request merged**
