### PR TITLE
[blog]: Kubeflow spark operator launch blog

### PR DESCRIPTION
**Pull request by vara-bonthu**
## Description

This PR introduces the launch blog post for the new [Kubeflow Spark Operator.](https://github.com/kubeflow/spark-operator) 

@andreyvelich

### CODE REVIEW

**Comment by jbottum** [comment]
I gave it a quick read.   Looks pretty good.   Will read again and provide any detailed comments.  Thanks for driving this!

**Comment by andreyvelich** [comment]
We want to publish this blog post this week. Please let us know for any changes/suggestions.
/assign @kubeflow/wg-data-leads @kubeflow/kubeflow-steering-committee @StefanoFioravanzo @akgraner

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by vara-bonthu** [comment]
@terrytangyuan, the blog has been updated with the date for the first community meeting. Please review it, and if you're satisfied, it's ready for merge. Thank you!

@andreyvelich  @yuchaoran2011

**Review by andreyvelich — COMMENTED** [review]
We should be ready to merge it
/lgtm
/approve
@vara-bonthu @yuchaoran2011 Feel free to un-hold this PR when you are ready.

**Pull request merged**
